fase1 = [
    (3, "right"),
    (1, "up"),
    (2, "left"),
    (4, "up"),
    (1, "right"),
    (1, "up"),
    (4, "right"),
    (1, "down"),
    (1, "right"),
    (3, "down"),
    (2, "left"),
    (1, "down"),
    (1, "right")
]

fase2 = [
    (1, "right"),
    (6, "up"),
    (2, "right"),
    (2, "down"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "up"),
    (2, "right"),
    (1, "down"),
    (1, "right"),
    (3, "down"),
    (2, "left"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (1, "left")
]

fase3 = [
    (1, "right"),
    (1, "up"),
    (4, "right"),
    (3, "up"),
    (2, "left"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (6, "right")
]

fase4 = [
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (3, "up"),
    (2, "right"),
    (3, "down"),
    (2, "right"),
    (3, "up")
]

fase5 = [
    (1, "right"),
    (4, "up"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "up"),
    (2, "right"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (2, "down"),
    (1, "left"),
    (1, "down"),
    (1, "left"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (1, "right")
]

fase6 = [
    (1, "right"),
    (5, "up"),
    (2, "right"),
    (1, "down"),
    (2, "right"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (1, "right"),
    (2, "up"),
    (4, "right"),
    (3, "down"),
    (2, "left"),
    (3, "down"),
    (1, "right"),
    (2, "up"),
    (1, "left"),
    (1, "down"),
    (4, "left"),
    (1, "up"),
    (2, "right"),
    (1, "up"),
    (3, "left")
]

fase7 = [
    (2, "right"),
    (1, "up"),
    (1, "left"),
    (7, "up"),
    (2, "right"),
    (1, "down"),
    (3, "right"),
    (1, "up"),
    (2, "right"),
    (4, "down"),
    (1, "left"),
    (1, "down"),
    (1, "left"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (5, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
]

fase8 = [
    (2, "right"),
    (2, "up"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (2, "up"),
    (3, "right"),
    (1, "down"),
    (1, "right"),
    (2, "down"),
    (2, "left"),
    (2, "down"),
    (1, "right"),
    (1, "up"),
]