level1 = [
    (3, "right"),
    (1, "up"),
    (2, "left"),
    (4, "up"),
    (1, "right"),
    (1, "up"),
    (4, "right"),
    (1, "down"),
    (1, "right"),
    (3, "down"),
    (2, "left"),
    (1, "down"),
    (1, "right")
]

level2 = [
    (1, "right"),
    (6, "up"),
    (2, "right"),
    (2, "down"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "up"),
    (2, "right"),
    (1, "down"),
    (1, "right"),
    (3, "down"),
    (2, "left"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (1, "left")
]

level3 = [
    (1, "right"),
    (1, "up"),
    (4, "right"),
    (3, "up"),
    (2, "left"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (6, "right")
]

level4 = [
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (3, "up"),
    (2, "right"),
    (3, "down"),
    (2, "right"),
    (3, "up")
]

level5 = [
    (1, "right"),
    (4, "up"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "up"),
    (2, "right"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (2, "down"),
    (1, "left"),
    (1, "down"),
    (1, "left"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (1, "right")
]

level6 = [
    (1, "right"),
    (5, "up"),
    (2, "right"),
    (1, "down"),
    (2, "right"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (1, "right"),
    (2, "up"),
    (4, "right"),
    (3, "down"),
    (2, "left"),
    (3, "down"),
    (1, "right"),
    (2, "up"),
    (1, "left"),
    (1, "down"),
    (4, "left"),
    (1, "up"),
    (2, "right"),
    (1, "up"),
    (3, "left")
]

level7 = [
    (2, "right"),
    (1, "up"),
    (1, "left"),
    (7, "up"),
    (2, "right"),
    (1, "down"),
    (3, "right"),
    (1, "up"),
    (2, "right"),
    (4, "down"),
    (1, "left"),
    (1, "down"),
    (1, "left"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (5, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up")
]

level8 = [
    (2, "right"),
    (2, "up"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (2, "up"),
    (3, "right"),
    (1, "down"),
    (1, "right"),
    (2, "down"),
    (2, "left"),
    (2, "down"),
    (1, "right"),
    (1, "up")
]

level9 = [
    (1, "right"),
    (7, "up"),
    (4, "right"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (3, "down"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (2, "left"),
    (3, "down"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "right")
]

level10 = [
    (1, "right"),
    (5, "up"),
    (5, "right"),
    (4, "down"),
    (3, "left"),
    (1, "down"),
    (2, "right"),
    (1, "up"),
    (1, "left"),
    (3, "up"),
    (1, "left"),
    (2, "up")
]

level11 = [
    (1, "right"),
    (8, "up"),
    (6, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (5, "left"),
    (1, "down"),
    (1, "left"),
    (2, "down"),
    (2, "right"),
    (1, "up"),
    (3, "right"),
    (1, "down"),
    (2, "right"),
    (5, "down"),
    (1, "left"),
    (1, "up"),
    (1, "left"),
    (2, "up"),
    (1, "left"),
    (2, "down"),
    (1, "left"),
    (2, "up"),
    (1, "left"),
    (1, "down"),
    (2, "left"),
    (2, "down"),
    (1, "right")
]

level12 = [
    (2, "right"),
    (1, "up"),
    (2, "right"),
    (1, "down"),
    (2, "right"),
    (1, "up"),
    (1, "right"),
    (2, "up"),
    (1, "left"),
    (1, "up"),
    (2, "left"),
    (1, "down"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (2, "up"),
    (1, "right"),
    (1, "up"),
    (4, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (2, "left"),
    (1, "down")
]

level13 = [
    (2, "right"),
    (1, "up"),
    (2, "right"),
    (2, "up"),
    (1, "left"),
    (3, "up"),
    (3, "right"),
    (3, "down"),
    (1, "left"),
    (2, "down"),
    (2, "right"),
    (1, "down")
]

level14 = [
    (1, "right"),
    (3, "up"),
    (4, "right"),
    (1, "up"),
    (2, "left"),
    (1, "up"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (2, "left"),
    (3, "up"),
    (1, "right"),
    (1, "up"),
    (4, "right"),
    (1, "down"),
    (1, "right"),
    (3, "down"),
    (3, "left"),
    (2, "down")
]

level15 = [ 
    (3, "right"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "down"),
    (3, "right"),
    (2, "up"),
    (4, "left"),
    (1, "up"),
    (4, "right"),
    (7, "up"),
    (6, "left"),
    (4, "down"),
    (2, "right"),
    (2, "up"),
    (2, "right"),
    (1, "down"),
    (1, "left"),
    (1, "down"),
    (3, "left"),
    (4, "up"),
    (6, "right"),
    (7, "down"),
    (3, "left"),
    (1, "up"),
    (1, "right"),
    (1, "up"),
]

level16 = [
    (1, "right"),
    (3, "up"),
    (1, "right"),
    (3, "up"),
    (2, "left"),
    (1, "down"),
    (3, "right"),
    (1, "up"),
    (2, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (3, "right"),
    (1, "down"),
    (2, "right"),
    (2, "up"),
    (1, "left"),
    (4, "up"),
    (2, "right"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (2, "left"),
    (3, "up"),
    (1, "left"),
    (2, "up"),
    (2, "left"),
    (1, "down"),
    (2, "left"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (4, "right"),
    (3, "down"),
    (1, "right"),
    (1, "up"),
    (2, "left"),
    (1, "up"),
    (1, "right"),
    (3, "down"),
    (2, "left"),
    (2, "up"),
    (3, "right"),
    (3, "up"),
    (2, "right"),
    (1, "down")
]

level17 = [
    (1, "right"),
    (1, "up"),
    (1, "right"),
    (2, "up"),
    (1, "right"),
    (1, "down"),
    (1, "right"),
    (1, "up"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (2, "down"),
    (2, "right"),
    (2, "up"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (2, "down"),
    (2, "right"),
    (2, "up"),
    (1, "left"),
    (1, "up"),
    (1, "right"),
    (2, "down"),
    (3, "right"),
    (1, "down"),
    (1, "right"),
    (6, "up"),
    (1, "left"),
    (1, "up"),
    (6, "left"),
    (1, "down"),
    (2, "left"),
    (1, "down"),
    (1, "left"),
    (1, "up"),
    (3, "right"),
    (1, "up"),
    (7, "right"),
    (3, "down"),
    (3, "left"),
    (1, "up"),
    (1, "right"),
    (1, "down"),
    (1, "left"),
    (2, "up"),
    (1, "left")
]